version: '3'

services:
  app1:
    image: python:3.11
    build: ./app1/
    container_name: app1
    working_dir: /var/www/html/
    volumes:
      - ./app1/:/var/www/html/
      - socket:/tmp
    command: uwsgi --ini /var/www/html/uwsgi_app1.ini
    restart: always
    tty: true

  app2:
    image: python:3.11
    build: ./app2/
    container_name: app2
    working_dir: /var/www/html/
    volumes:
      - ./app2/:/var/www/html/
      - socket:/tmp
    command: uwsgi --ini /var/www/html/uwsgi_app2.ini
    restart: always
    tty: true

  nginx:
    image: nginx:latest
    ports:
      - "5000:5000"
      - "5001:5001"
      - "80:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - socket:/tmp

volumes:
  socket: