version: '3'

services:
  app1:
    image: python:3.11
    build: ./app1/
    container_name: app1
    working_dir: /var/www/html/
    volumes:
      - ./web/:${ROOT_PATH}
      - socket:/tmp
    command: uwsgi --ini /var/www/html/uwsgi.ini
    restart: always
    tty: true

  nginx:
    image: nginx:latest
    ports:
      - "5000:5000"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - socket:/tmp

volumes:
  socket: